### ISSUE TITLE
Pods are inaccessible after install

### ISSUE THREAD

**Issue by aleiner** [rancherfederal/carbide-docs#112]
With the exception of NeuVector VDB, all of the airgap docs pods are inaccessible (via curl or the AirGap docs portal). Looking at the logs on any of those pods, they all say:

"...Address family not supported by protocol". Without shell access to the pods, I wasn't able to troubleshoot any further at the time.

Research may point to a possible IPv6 issue - https://github.com/nginxinc/kubernetes-ingress/issues/2970

I believe this customer has IPv6 disabled, but will check next time I'm on site.

@zackbradys

**Comment by zackbradys** [comment]
closing as resolved per PR https://github.com/rancherfederal/carbide-charts/pull/232!
